### ISSUE TITLE
Something seems off with the rendering

### ISSUE THREAD

**Issue by neuroradiology** [jsulpis/realtime-planet-shader#7]
When I look at the moon and watch a landmark near the equator leave the horizon on the right and become hidden, it comes back up on the left side WAY sooner than I would expect. Is it just an illusion? I trust the 3d mapping better than my eye, but it looks really strange / off.

**Comment by jsulpis** [comment]
Well, don't trust the mapping too much 😅
I also noticed an issue and the sphere projection is indeed incorrect. I'm trying to figure out how to fix that !

**Comment by jsulpis** [comment]
I forgot to do a PR but it should be fixed by https://github.com/jsulpis/realtime-planet-shader/commit/f4944b37f307225cb9a7e8a8ce07cb75f08ff420.
Thank you for reporting the issue !
